### ISSUE TITLE
Open modal outside of setup function?

### ISSUE THREAD

**Issue by ideafm** [vue-final/vue-final-modal#331]
Hi! Is it possible to create/open modal outside of setup function? What if I using options API without setup function? 

### Version
vue-final-modal: 4.0.4
vue: 3.2.47
nuxt: 3.1.2

### OS
Mac

**Comment by hunterliu1003** [comment]
Hi @ideafm 

Yes it is! But you have to use it carefully. Because it might cause memory leak.

In short answer:

1. You need to export `vfm` instance while register the `vue-final-modal` plugin like so:

```ts
import { createVfm } from 'vue-final-modal'
import { defineNuxtPlugin } from '#app'

export const vfm = createVfm() as any
export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.use(vfm)
})
```

2. Then you should pass the `vfm` instance to the `options.context` in `useModal(options)`, you have to manually `destroy()` the `modalInstance` after you don't need the dynamic modal anymore, like so:

```ts
// Anywhere outside out script setup
import { VueFinalModal, useModal } from 'vue-final-modal'
import { vfm } from '@/plugins/vue-final-modal'

export function openModalConfirm() {
  const modalInstance = useModal({
    context: vfm,
    attrs: {
      onClosed() {
        // This will avoid the memory leak
        modalInstance.destroy()
      },
    }
  })
  modalInstance.open()
}
```

For more detail, you can follow the Nuxt part of [Edge case ](https://vue-final-modal.org/api/composables/use-modal#edge-usage) in the documentation.

**Comment by hunterliu1003** [comment]
If you just need to extract the logic out of `script setup`.
I recommend to create a function like: 

```ts
export function openModalOutsideSetupScript(vfm: Vfm) {
  const modalInstance = useModal({
    context: vfm,
    attrs: {
      onClosed() {
        modalInstance.destroy()
      },
    }
  })
  modalInstance.open()
}
```

```vue
<script setup>
import { useVfm } from 'vue-final-modal'

const vfm = useVfm()

openModalOutsideSetupScript(vfm)
</script>
```

**Comment by ideafm** [comment]
Sorry, I was missing Edge section of docs. 
Thanks!

**Comment by ideafm** [comment]
But, with this approach, I have a hydration issue via SSR

```
[Vue warn]: Hydration node mismatch:
- Client vnode: Symbol(Fragment) 
- Server rendered DOM: <!---->  
  at <ModalsContainer> 
  at <Default > 
  at <LayoutLoader key="default" name="default" hasTransition=false > 
  at <FragmentWrapper > 
  at <NuxtLayout> 
  at <App key=2 > 
  at <NuxtRoot>
```

**Comment by ideafm** [comment]
Here is reproduction https://stackblitz.com/edit/nuxt-starter-apdmrl?file=nuxt.config.ts,plugins%2Fmodals.js,utils%2FshowModal.js,app.vue,components%2Fmodals%2FTestModal.vue

**Comment by hunterliu1003** [comment]
@ideafm 


> Here is reproduction https://stackblitz.com/edit/nuxt-starter-apdmrl?file=nuxt.config.ts,plugins%2Fmodals.js,utils%2FshowModal.js,app.vue,components%2Fmodals%2FTestModal.vue

I just tried your reproduction, I don't see the hydration node mismatch error.
Can you upload a screenshot or some steps how to reproduce the error?

**Comment by ideafm** [comment]
Ofcourse. Open this stackblitz in new window and open console.

![Снимок экрана 2023-02-20 в 14 13 04](https://user-images.githubusercontent.com/6522186/220091138-5a81cde4-8a9b-4684-872f-1943b16de2df.png)

**Comment by hunterliu1003** [comment]
@ideafm 
I don't have the issue. 😳

<img width="2046" alt="image" src="https://user-images.githubusercontent.com/15190246/220095122-7239eb1d-c085-4f9c-a4c5-9d60a0d6272d.png">

**Comment by hunterliu1003** [comment]
@ideafm 

I just found that the documentation is wrong, we can't do this: 
<img width="410" alt="image" src="https://user-images.githubusercontent.com/15190246/220098499-3126adba-68a3-4904-ac71-d942c237e91c.png">
We have to move `createVfm()` inside of `defineNuxtPlugin` like so:
<img width="411" alt="image" src="https://user-images.githubusercontent.com/15190246/220098210-c6cfa7a7-9198-471b-85bd-87dfd7fee7d9.png">

Instead of import vfm instance from `/plugins/modals.js`, you can use `this.$vfm` to get the vfm instance.
So the showModal should be fix as: 

```ts
export default {
  components: {
    ModalsContainer,
  },
  methods: {
    show() {
      showModal(this.$vfm, TestModal, { testProp: '[test prop]' });
    },
  },
};
```

I fixed it here: https://stackblitz.com/edit/nuxt-starter-gjkl4c?file=plugins%2Fmodals.js&file=app.vue&file=utils%2FshowModal.js

I'll also update the documentation later

**Comment by ideafm** [comment]
Ok, now it works fine.
As replacement vue-js-modal, this code could be helpful 
```
import { createVfm, useModal } from 'vue-final-modal';

const showModal = (context, component, props = {}) => {
  const modalInstance = useModal({
    context,
    component,
    attrs: {
      ...props,
      onClosed() {
        modalInstance.destroy();
      },
      onClose() {
        modalInstance.close();
      },
    },
  });
  modalInstance.open();

  return modalInstance;
};

export default defineNuxtPlugin((nuxtApp) => {
  const vfm = createVfm();
  nuxtApp.vueApp.use(vfm);

  return {
    provide: {
      modal: {
        show: (comp, props = {}) => showModal(vfm, comp, props),
      },
    },
  };
});
```
and just `this.$modal.show(Component, { ...someProps })`
