### ISSUE TITLE
Swipe event

### ISSUE THREAD

**Issue by lyneal** [vue-final/vue-final-modal#339]
Hello,

Would it be possible to add events related to the "swipeToClose" functionality? The idea is to let the possibility to trigger a function when the modal is swiped  (not necessarily to close the modal).

I propose two different solutions:
- One event per swipe direction (@swipeUp, @swipeDown, @swipeRight, @swipeLeft)
- A single event that provides a parameter specifying the swipe direction (@swipe).

Thanks in advance for your feedback and your work on this project.

**Comment by hunterliu1003** [comment]
Thanks for you suggestion. I am sorry that currently I don't plan to bring more props or events relate to swipe, everytime I add new props or events, it brings more feature request for more usage of edge cases. I want to keep VueFinalModal as simple as possible (because it's already complex to me) 😅. If you really need this feature, you can create a HOC yourself with useSwipe in vueuse.
