### ISSUE TITLE
Make modal draggable and resizable please

### ISSUE THREAD

**Issue by claudemangen** [vue-final/vue-final-modal#64]
Hello,

thank you ver much for this fantastic modal. Great work!

Is it still planned to make the modal draggable and resizable?
You mentioned it in this post #8 , but in the [Roadmap](https://github.com/vue-final/vue-final-modal/projects/1) it is not present any more.

P.S.: Your "by me a coffee" sit is not working correctly.

Thank you.

**Comment by hunterliu1003** [comment]
Hi @claudemangen,

> thank you ver much for this fantastic modal. Great work!

Thanks for your encouragement.

> Is it still planned to make the modal draggable and resizable?
> You mentioned it in this post #8 , but in the [Roadmap](https://github.com/vue-final/vue-final-modal/projects/1) it is not present any more.

When I was planning this project at the beginning, I actually wanted to have built-in support for draggable and resizable modal, just like vue-js-modal.
However, since vue-final-modal is a renderless component, this means that I cannot control the content passed in by the developer. At the beginning of development, I think it is not common to use modal with draggable and resizable.
I think a good way is to write directives to support draggable and resizable modal. If you really need these two features, I will add a few examples to the document.

> P.S.: Your "by me a coffee" sit is not working correctly.

Actually, I didn't seriously think that someone would sponsor me, so I didn't bind paypal account. I just think it’s cool to put `buy me a coffee` in the readme. :joy:

**Comment by claudemangen** [comment]
Hello,

yes this would be cool if you could add some examples in the documentation to make the modal draggable and resizable 😀

**Comment by hunterliu1003** [comment]
The feature was released in

- [v2.3.0](https://github.com/vue-final/vue-final-modal/releases/tag/v2.3.0) for Vue 2
- [v3.3.0](https://github.com/vue-final/vue-final-modal/releases/tag/v3.3.0) for Vue 3
